import com.sun.net.httpserver.Headers;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.*;
import java.net.InetSocketAddress;
import java.net.URLConnection;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

public class WebServer {
    private static final int PORT = 3000;
    private static final String[] CARD_NAMES = new String[]{
            "apple","banana","cherry","grapes","mango","orange","papaya","pineapple","strawberry","watermelon"
    };

    public static void main(String[] args) throws Exception {
        HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 0);

        server.createContext("/api/status", new StatusHandler());
        server.createContext("/api/cards", new CardsHandler());
        server.createContext("/img/", new ImageHandler());
        server.createContext("/", new StaticHandler());

        server.setExecutor(null);
        server.start();
        System.out.println("MatchCards Java backend listening on http://localhost:" + PORT);
        // keep main thread alive
        try {
            new java.util.concurrent.CountDownLatch(1).await();
        } catch (InterruptedException ex) {
            // shut down on interrupt
            server.stop(0);
        }
    }

    static class StatusHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if (!"GET".equalsIgnoreCase(exchange.getRequestMethod())) {
                exchange.sendResponseHeaders(405, -1);
                return;
            }
            String resp = "{\"status\":\"ok\",\"name\":\"MatchCards Java backend\"}";
            byte[] bytes = resp.getBytes("UTF-8");
            Headers h = exchange.getResponseHeaders();
            h.set("Content-Type", "application/json; charset=utf-8");
            h.set("Access-Control-Allow-Origin", "*");
            exchange.sendResponseHeaders(200, bytes.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(bytes);
            }
        }
    }

    static class CardsHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if (!"GET".equalsIgnoreCase(exchange.getRequestMethod())) {
                exchange.sendResponseHeaders(405, -1);
                return;
            }
            List<String> items = new ArrayList<>();
            Path projectRoot = Paths.get(System.getProperty("user.dir")).toAbsolutePath();
            for (String n : CARD_NAMES) {
                // prefer svg if present (search multiple folders), otherwise use jpg path
                Path svgPath = resolveImage(projectRoot, n + ".svg");
                Path jpgPath = resolveImage(projectRoot, n + ".jpg");
                String imgPath = "/img/" + n + ".jpg";
                if (svgPath != null && Files.exists(svgPath)) imgPath = "/img/" + n + ".svg";
                else if (jpgPath != null && Files.exists(jpgPath)) imgPath = "/img/" + n + ".jpg";
                else imgPath = "/img/" + n + ".jpg"; // placeholder generated by ImageHandler when missing
                String obj = String.format("{\"name\":\"%s\",\"image\":\"%s\"}", n, imgPath);
                items.add(obj);
            }
            String body = "[" + String.join(",", items) + "]";
            byte[] bytes = body.getBytes("UTF-8");
            Headers h = exchange.getResponseHeaders();
            h.set("Content-Type", "application/json; charset=utf-8");
            h.set("Access-Control-Allow-Origin", "*");
            exchange.sendResponseHeaders(200, bytes.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(bytes);
            }
        }
    }

    static class ImageHandler implements HttpHandler {
        private final Path projectRoot = Paths.get(System.getProperty("user.dir")).toAbsolutePath();

        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if (!"GET".equalsIgnoreCase(exchange.getRequestMethod())) {
                exchange.sendResponseHeaders(405, -1);
                return;
            }
            String uriPath = exchange.getRequestURI().getPath(); // /img/name.jpg
            String rel = uriPath.replaceFirst("/img/", "");
            // sanitize
            if (rel.contains("..")) {
                exchange.sendResponseHeaders(400, -1);
                return;
            }
                Path imgPath = projectRoot.resolve("img").resolve(rel);
                // if top-level img doesn't exist, also try src/img and bin/img
                if (!Files.exists(imgPath) || Files.isDirectory(imgPath)) {
                    Path alt = resolveImage(projectRoot, rel);
                    if (alt != null && Files.exists(alt) && !Files.isDirectory(alt)) {
                        imgPath = alt;
                    }
                }
                Headers h = exchange.getResponseHeaders();
                // if requested file doesn't exist, try same name but .svg
                if (!Files.exists(imgPath) || Files.isDirectory(imgPath)) {
                    String alt = rel.replaceAll("\\.[^.]+$", "") + ".svg";
                    Path altPath = resolveImage(projectRoot, alt);
                    if (altPath != null && Files.exists(altPath) && !Files.isDirectory(altPath)) {
                        imgPath = altPath;
                    } else {
                        // generate a simple SVG placeholder when file is missing
                        String title = rel.replaceAll("\\.[^.]+$", "");
                        String svg = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                                "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"120\" height=\"160\">" +
                                "<rect width=\"100%\" height=\"100%\" fill=\"#f5f5f5\" stroke=\"#ddd\"/>" +
                                "<text x=\"50%\" y=\"50%\" dominant-baseline=\"middle\" text-anchor=\"middle\" fill=\"#555\" font-family=\"Arial, Helvetica, sans-serif\" font-size=\"16\">" + escapeXml(title) + "</text>" +
                                "</svg>";
                        byte[] svgBytes = svg.getBytes("UTF-8");
                        h.set("Content-Type", "image/svg+xml; charset=utf-8");
                        h.set("Cache-Control", "no-cache");
                        exchange.sendResponseHeaders(200, svgBytes.length);
                        try (OutputStream os = exchange.getResponseBody()) {
                            os.write(svgBytes);
                        }
                        return;
                    }
                }
            String mime = URLConnection.guessContentTypeFromName(imgPath.toString());
            if (mime == null) mime = "application/octet-stream";
            h.set("Content-Type", mime);
            h.set("Cache-Control", "no-cache");
            exchange.sendResponseHeaders(200, Files.size(imgPath));
            try (OutputStream os = exchange.getResponseBody(); InputStream is = Files.newInputStream(imgPath)) {
                byte[] buffer = new byte[8192];
                int read;
                while ((read = is.read(buffer)) != -1) {
                    os.write(buffer, 0, read);
                }
            }
        }
    }

    static class StaticHandler implements HttpHandler {
        private final Path projectRoot = Paths.get(System.getProperty("user.dir")).toAbsolutePath();

        @Override
        public void handle(HttpExchange exchange) throws IOException {
            String method = exchange.getRequestMethod();
            if (!"GET".equalsIgnoreCase(method)) {
                exchange.sendResponseHeaders(405, -1);
                return;
            }
            String uri = exchange.getRequestURI().getPath();
            if (uri.equals("/")) uri = "/index.html";
            // map to frontend folder by default
            Path file = projectRoot.resolve("frontend").resolve(uri.replaceFirst("/",""));
            if (!Files.exists(file) || Files.isDirectory(file)) {
                // fallback to index.html for SPA
                file = projectRoot.resolve("frontend").resolve("index.html");
            }
            if (!Files.exists(file)) {
                exchange.sendResponseHeaders(404, -1);
                return;
            }
            String mime = URLConnection.guessContentTypeFromName(file.toString());
            if (mime == null) mime = "application/octet-stream";
            Headers h = exchange.getResponseHeaders();
            h.set("Content-Type", mime + "; charset=utf-8");
            h.set("Access-Control-Allow-Origin", "*");
            exchange.sendResponseHeaders(200, Files.size(file));
            try (OutputStream os = exchange.getResponseBody(); InputStream is = Files.newInputStream(file)) {
                byte[] buffer = new byte[8192];
                int read;
                while ((read = is.read(buffer)) != -1) {
                    os.write(buffer, 0, read);
                }
            }
        }
    }

    private static String escapeXml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
    }

    /**
     * Resolve an image filename by searching common project locations: top-level img/, src/img/, bin/img/.
     * Returns the first Path (not necessarily existing) to be used for existence checks elsewhere.
     */
    private static Path resolveImage(Path projectRoot, String filename) {
        if (filename == null) return null;
        Path p1 = projectRoot.resolve("img").resolve(filename);
        Path p2 = projectRoot.resolve("src").resolve("img").resolve(filename);
        Path p3 = projectRoot.resolve("bin").resolve("img").resolve(filename);
        if (Files.exists(p1)) return p1;
        if (Files.exists(p2)) return p2;
        if (Files.exists(p3)) return p3;
        // none exist, prefer top-level path as a default (used to build URL path only)
        return p1;
    }

}
